# Generated by Django 2.2.7 on 2019-11-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20191122_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tipoPersona',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
