# Generated by Django 2.2.7 on 2019-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20191125_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='web',
            field=models.CharField(max_length=50),
        ),
    ]
