# Generated by Django 2.2.7 on 2019-11-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20191125_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='cumple',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='soporte',
        ),
    ]
