# Generated by Django 2.2.7 on 2019-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
